# Generated by Django 2.2.1 on 2019-11-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryb',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livestock.CategoryA', verbose_name='Category A'),
            preserve_default=False,
        ),
    ]
