# Generated by Django 2.2.1 on 2019-11-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_livestockdisease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockdisease',
            old_name='constrol_measures',
            new_name='control_measures',
        ),
    ]
