# Generated by Django 2.2.1 on 2019-11-09 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191109_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 14, 13, 29, 552464)),
        ),
    ]
