# Generated by Django 2.2.1 on 2019-11-09 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191109_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 18, 19, 19, 618298)),
        ),
    ]
